import type { MarkupInfo, ReferenceType } from "./defs";


export type SalesItemLine = {
	/**
	 * The Id of the line item.
	 * If Id > 0 and exists, treated as update for the line item.
	 * If missing, <= 0, or non-existent, treated as create for the line item.
	 * Available in all objects that use lines and support update.
	 * @requiredForUpdate
	 * @systemDefined
	 */
	readonly Id?: string;
	/**
	 * Set to SalesItemLineDetail for this type of line.
	 * LineDetailTypeEnum
	 */
	DetailType: "SalesItemLineDetail";
	/**
	 * Sales item line detail (see SalesItemLineDetail).
	 */
	SalesItemLineDetail: SalesItemLineDetail;
	/**
	 * The amount of the line item.
	 * Max 15 digits in 10.5 format.
	 */
	Amount: number;
	/**
	 * Free form text description of the line item that appears in the printed record.
	 * @max 4000 characters
	 */
	Description?: string;
	/**
	 * Position of the line in the collection of transaction lines. Positive integer.
	 */
	LineNum?: number;
}

export type GroupLine = {
	/**
	 * The Id of the line item.
	 * @requiredForUpdate
	 * @systemDefined
	 */
	readonly Id?: string;
	/**
	 * Group line detail.
	 */
	GroupLineDetail: GroupLineDetail;
	/**
	 * Set to GroupLineDetail for this type of line.
	 * LineDetailTypeEnum
	 */
	DetailType: "GroupLineDetail";
	/**
	 * Position of the line in the collection of transaction lines. Positive integer.
	 */
	LineNum?: number;
	/**
	 * Free form text description of the line item that appears in the printed record.
	 * @max 4000 characters
	 */
	Description?: string;
}

export type DescriptionOnlyLine = {
	/**
	 * The Id of the line item.
	 * @requiredForUpdate
	 * @systemDefined
	 */
	readonly Id?: string;
	/**
	 * Set to DescriptionOnly for this type of line.
	 * LineDetailTypeEnum
	 */
	DetailType: "DescriptionOnly";
	/**
	 * Description-only line detail.
	 */
	DescriptionLineDetail: DescriptionLineDetail;
	/**
	 * A string representing either free form description or an inline subtotal line.
	 * For subtotal: in create requests, set to "Subtotal:"; the amount is generated by QBO.
	 * @max 4000 characters
	 */
	Description?: string;
	/**
	 * Position of the line in the collection of transaction lines. Positive integer.
	 */
	LineNum?: number;
	/**
	 * The amount of the line item when set via the QuickBooks UI.
	 * Returned only for Description Only line items that have a non-empty amount.
	 * @minorVersion 23
	 */
	readonly Amount?: number;
}

export type DiscountLine = {
	/**
	 * The Id of the line item.
	 * @requiredForUpdate
	 * @systemDefined
	 */
	readonly Id?: string;
	/**
	 * Discount detail type for the entire transaction.
	 */
	DiscountLineDetail: DiscountLineDetail;
	/**
	 * Set to DiscountLineDetail for this type of line.
	 * LineDetailTypeEnum
	 */
	DetailType: "DiscountLineDetail";
	/**
	 * The amount of the line item.
	 * Max 15 digits in 10.5 format.
	 */
	Amount: number;
	/**
	 * Free form text description of the line item that appears in the printed record.
	 * @max 4000 characters
	 */
	Description?: string;
	/**
	 * Position of the line in the collection of transaction lines. Positive integer.
	 */
	LineNum?: number;
}

export type SubTotalLine = {
	/**
	 * The Id of the line item.
	 * @requiredForUpdate
	 * @systemDefined
	 */
	readonly Id?: string;
	/**
	 * Subtotal LineDetail
	 */
	SubTotalLineDetail: SubTotalLineDetail;
	/**
	 * Set to SubTotalLineDetail for this type of line.
	 * LineDetailTypeEnum
	 */
	DetailType: "SubTotalLineDetail";
	/**
	 * The amount of the line item.
	 * Max 15 digits in 10.5 format.
	 */
	Amount: number;
	/**
	 * Free form text description of the line item that appears in the printed record.
	 * @max 4000 characters
	 */
	Description?: string;
	/**
	 * Position of the line in the collection of transaction lines. Positive integer.
	 */
	LineNum?: number;
}

export type TransactionLine = SalesItemLine | GroupLine | DescriptionOnlyLine | DiscountLine | SubTotalLine;


export type SalesItemLineDetail = {
	/**
	 * The total amount of the line item including tax.
	 * @minorVersion 1
	 */
	TaxInclusiveAmt?: number;
	/**
	 * The discount amount applied to this line.
	 * If both DiscountAmt and DiscountRate are supplied, DiscountRate takes precedence.
	 * @minorVersion 4
	 */
	DiscountAmt?: number;
	ItemRef?: ReferenceType;
	ClassRef?: ReferenceType;
	TaxCodeRef?: ReferenceType;
	ServiceDate?: string;
	/**
	 * The discount rate applied to this line.
	 * If both DiscountAmt and DiscountRate are supplied, DiscountRate takes precedence.
	 * @minorVersion 4
	 */
	DiscountRate?: number;
	Qty?: number;
	UnitPrice?: number;
	readonly TaxClassificationRef?: ReferenceType;
	ItemAccountRef?: ReferenceType;
	/**
	 * Markup information for the billable expense line.
	 */
	MarkupInfo?: MarkupInfo;
}

export type GroupLineDetail = {
	/**
	 * Quantity of the group item.
	 */
	Quantity?: number;
	/**
	 * Individual ItemLine elements that comprise a bundle (returned in responses).
	 */
	Line?: SalesItemLine[];
	/**
	 * Reference to a group item for all the lines that belong to the bundle.
	 */
	GroupItemRef?: ReferenceType;
}

export type DescriptionLineDetail = {
	/**
	 * Reference to the TaxCode for this item.
	 */
	TaxCodeRef?: ReferenceType;
	/**
	 * Date when the service is performed.
	 */
	ServiceDate?: string;
}

export type DiscountLineDetail = {
	/**
	 * Reference to the Class associated with this discount.
	 */
	ClassRef?: ReferenceType;
	/**
	 * TaxCode associated with the sales tax for the expense.
	 */
	TaxCodeRef?: ReferenceType;
	/**
	 * Income account used to track discounts.
	 */
	DiscountAccountRef?: ReferenceType;
	/**
	 * True if the discount is percentage-based.
	 * False/null if based on amount.
	 */
	PercentBased?: boolean;
	/**
	 * Percentage by which the amount due is reduced (e.g., 8.5 for 8.5%).
	 */
	DiscountPercent?: number;
}

export type SubTotalLineDetail = {
	/**
	 * Reference to the Item. When a line lacks an ItemRef it is treated as
	 * documentation and the Line.Amount attribute is ignored.
	 */
	ItemRef?: ReferenceType;
}

export type { TransactionLine as default };