import { Account } from '../../src/app';

// Mock Account Data
export const mockAccountData: Array<Account> = [
	{
		Id: '1',
		Name: 'Checking Account',
		FullyQualifiedName: 'Checking Account',
		domain: 'QBO',
		Classification: 'Asset',
		AccountType: 'Bank',
		AccountSubType: 'Checking',
		CurrencyRef: {
			name: 'United States Dollar',
			value: 'USD',
		},
		CurrentBalance: 1000,
		CurrentBalanceWithSubAccounts: 1000,
		sparse: false,
		Active: true,
		SyncToken: '0',
		SubAccount: false,
		MetaData: {
			CreateTime: '2021-01-01T00:00:00Z',
			LastUpdatedTime: '2022-01-10T00:00:00Z',
		},
	},
	{
		Id: '2',
		Name: 'Savings Account',
		FullyQualifiedName: 'Savings Account',
		domain: 'QBO',
		Classification: 'Asset',
		AccountType: 'Bank',
		AccountSubType: 'Savings',
		CurrencyRef: {
			name: 'United States Dollar',
			value: 'USD',
		},
		CurrentBalance: 5000,
		CurrentBalanceWithSubAccounts: 5000,
		sparse: false,
		Active: true,
		SyncToken: '0',
		SubAccount: false,
		MetaData: {
			CreateTime: '2020-01-02T00:00:00Z',
			LastUpdatedTime: '2025-01-11T00:00:00Z',
		},
	},
	{
		Id: '3',
		Name: 'Accounts Receivable',
		FullyQualifiedName: 'Accounts Receivable',
		domain: 'QBO',
		Classification: 'Asset',
		AccountType: 'Accounts Receivable',
		AccountSubType: 'AccountsReceivable',
		CurrencyRef: {
			name: 'United States Dollar',
			value: 'USD',
		},
		CurrentBalance: 2500,
		CurrentBalanceWithSubAccounts: 2500,
		sparse: false,
		Active: true,
		SyncToken: '0',
		SubAccount: false,
		MetaData: {
			CreateTime: '2019-01-03T00:00:00Z',
			LastUpdatedTime: '2024-01-08T00:00:00Z',
		},
	},
	{
		Id: '4',
		Name: 'Office Supplies',
		FullyQualifiedName: 'Office Supplies',
		domain: 'QBO',
		Classification: 'Expense',
		AccountType: 'Expense',
		AccountSubType: 'OfficeSupplies',
		CurrencyRef: {
			name: 'United States Dollar',
			value: 'USD',
		},
		CurrentBalance: 350.75,
		CurrentBalanceWithSubAccounts: 350.75,
		sparse: false,
		Active: true,
		SyncToken: '0',
		SubAccount: false,
		MetaData: {
			CreateTime: '2023-01-04T00:00:00Z',
			LastUpdatedTime: '2024-01-07T00:00:00Z',
		},
	},
	{
		Id: '5',
		Name: 'Sales Revenue',
		FullyQualifiedName: 'Sales Revenue',
		domain: 'QBO',
		Classification: 'Revenue',
		AccountType: 'Income',
		AccountSubType: 'SalesOfProductIncome',
		CurrencyRef: {
			name: 'United States Dollar',
			value: 'USD',
		},
		CurrentBalance: 7500,
		CurrentBalanceWithSubAccounts: 7500,
		sparse: false,
		Active: true,
		SyncToken: '0',
		SubAccount: false,
		MetaData: {
			CreateTime: '2018-01-05T00:00:00Z',
			LastUpdatedTime: '2025-01-05T00:00:00Z',
		},
	},
	{
		Id: '6',
		Name: 'Sales Revenue',
		FullyQualifiedName: 'Sales Revenue',
		domain: 'QBO',
		Classification: 'Revenue',
		AccountType: 'Income',
		AccountSubType: 'SalesOfProductIncome',
		CurrencyRef: {
			name: 'United States Dollar',
			value: 'USD',
		},
		CurrentBalance: 7500,
		CurrentBalanceWithSubAccounts: 7500,
		sparse: false,
		Active: true,
		SyncToken: '0',
		SubAccount: false,
		MetaData: {
			CreateTime: '2018-01-05T00:00:00Z',
			LastUpdatedTime: '2025-01-05T00:00:00Z',
		},
	},
	{
		Id: '7',
		Name: 'Sales Revenue',
		FullyQualifiedName: 'Sales Revenue',
		domain: 'QBO',
		Classification: 'Revenue',
		AccountType: 'Income',
		AccountSubType: 'SalesOfProductIncome',
		CurrencyRef: {
			name: 'United States Dollar',
			value: 'USD',
		},
		CurrentBalance: 7500,
		CurrentBalanceWithSubAccounts: 7500,
		sparse: false,
		Active: true,
		SyncToken: '0',
		SubAccount: false,
		MetaData: {
			CreateTime: '2018-01-05T00:00:00Z',
			LastUpdatedTime: '2025-01-05T00:00:00Z',
		},
	},
	{
		Id: '8',
		Name: 'Sales Revenue',
		FullyQualifiedName: 'Sales Revenue',
		domain: 'QBO',
		Classification: 'Revenue',
		AccountType: 'Income',
		AccountSubType: 'SalesOfProductIncome',
		CurrencyRef: {
			name: 'United States Dollar',
			value: 'USD',
		},
		CurrentBalance: 7500,
		CurrentBalanceWithSubAccounts: 7500,
		sparse: false,
		Active: true,
		SyncToken: '0',
		SubAccount: false,
		MetaData: {
			CreateTime: '2018-01-05T00:00:00Z',
			LastUpdatedTime: '2025-01-05T00:00:00Z',
		},
	},
	{
		Id: '9',
		Name: 'Sales Revenue',
		FullyQualifiedName: 'Sales Revenue',
		domain: 'QBO',
		Classification: 'Revenue',
		AccountType: 'Income',
		AccountSubType: 'SalesOfProductIncome',
		CurrencyRef: {
			name: 'United States Dollar',
			value: 'USD',
		},
		CurrentBalance: 7500,
		CurrentBalanceWithSubAccounts: 7500,
		sparse: false,
		Active: true,
		SyncToken: '0',
		SubAccount: false,
		MetaData: {
			CreateTime: '2018-01-05T00:00:00Z',
			LastUpdatedTime: '2025-01-05T00:00:00Z',
		},
	},
	{
		Id: '10',
		Name: 'Sales Revenue',
		FullyQualifiedName: 'Sales Revenue',
		domain: 'QBO',
		Classification: 'Revenue',
		AccountType: 'Income',
		AccountSubType: 'SalesOfProductIncome',
		CurrencyRef: {
			name: 'United States Dollar',
			value: 'USD',
		},
		CurrentBalance: 7500,
		CurrentBalanceWithSubAccounts: 7500,
		sparse: false,
		Active: true,
		SyncToken: '0',
		SubAccount: false,
		MetaData: {
			CreateTime: '2018-01-05T00:00:00Z',
			LastUpdatedTime: '2025-01-05T00:00:00Z',
		},
	},
	{
		Id: '11',
		Name: 'Sales Revenue',
		FullyQualifiedName: 'Sales Revenue',
		domain: 'QBO',
		Classification: 'Revenue',
		AccountType: 'Income',
		AccountSubType: 'SalesOfProductIncome',
		CurrencyRef: {
			name: 'United States Dollar',
			value: 'USD',
		},
		CurrentBalance: 7500,
		CurrentBalanceWithSubAccounts: 7500,
		sparse: false,
		Active: true,
		SyncToken: '0',
		SubAccount: false,
		MetaData: {
			CreateTime: '2018-01-05T00:00:00Z',
			LastUpdatedTime: '2025-01-05T00:00:00Z',
		},
	},
	{
		Id: '12',
		Name: 'Sales Revenue',
		FullyQualifiedName: 'Sales Revenue',
		domain: 'QBO',
		Classification: 'Revenue',
		AccountType: 'Income',
		AccountSubType: 'SalesOfProductIncome',
		CurrencyRef: {
			name: 'United States Dollar',
			value: 'USD',
		},
		CurrentBalance: 7500,
		CurrentBalanceWithSubAccounts: 7500,
		sparse: false,
		Active: true,
		SyncToken: '0',
		SubAccount: false,
		MetaData: {
			CreateTime: '2018-01-05T00:00:00Z',
			LastUpdatedTime: '2025-01-05T00:00:00Z',
		},
	},
	{
		Id: '13',
		Name: 'Sales Revenue',
		FullyQualifiedName: 'Sales Revenue',
		domain: 'QBO',
		Classification: 'Revenue',
		AccountType: 'Income',
		AccountSubType: 'SalesOfProductIncome',
		CurrencyRef: {
			name: 'United States Dollar',
			value: 'USD',
		},
		CurrentBalance: 7500,
		CurrentBalanceWithSubAccounts: 7500,
		sparse: false,
		Active: true,
		SyncToken: '0',
		SubAccount: false,
		MetaData: {
			CreateTime: '2018-01-05T00:00:00Z',
			LastUpdatedTime: '2025-01-05T00:00:00Z',
		},
	},
	{
		Id: '14',
		Name: 'Sales Revenue',
		FullyQualifiedName: 'Sales Revenue',
		domain: 'QBO',
		Classification: 'Revenue',
		AccountType: 'Income',
		AccountSubType: 'SalesOfProductIncome',
		CurrencyRef: {
			name: 'United States Dollar',
			value: 'USD',
		},
		CurrentBalance: 7500,
		CurrentBalanceWithSubAccounts: 7500,
		sparse: false,
		Active: true,
		SyncToken: '0',
		SubAccount: false,
		MetaData: {
			CreateTime: '2018-01-05T00:00:00Z',
			LastUpdatedTime: '2025-01-05T00:00:00Z',
		},
	},
	{
		Id: '15',
		Name: 'Sales Revenue',
		FullyQualifiedName: 'Sales Revenue',
		domain: 'QBO',
		Classification: 'Revenue',
		AccountType: 'Income',
		AccountSubType: 'SalesOfProductIncome',
		CurrencyRef: {
			name: 'United States Dollar',
			value: 'USD',
		},
		CurrentBalance: 7500,
		CurrentBalanceWithSubAccounts: 7500,
		sparse: false,
		Active: true,
		SyncToken: '0',
		SubAccount: false,
		MetaData: {
			CreateTime: '2018-01-05T00:00:00Z',
			LastUpdatedTime: '2025-01-05T00:00:00Z',
		},
	},
];
