// Imports
import type { Customer } from '../../src/app';

// Export the Mock Customer Data
export const mockCustomerData: Array<Customer> = [
	{
		PrimaryEmailAddr: {
			Address: 'ocean@seashop.com',
		},
		SyncToken: '1',
		domain: 'QBO',
		GivenName: 'Alice',
		DisplayName: "Alice's Ocean Shop",
		BillWithParent: false,
		FullyQualifiedName: "Alice's Ocean Shop",
		CompanyName: "Alice's Ocean Shop",
		FamilyName: 'Johnson',
		sparse: false,
		PrimaryPhone: {
			FreeFormNumber: '(415) 555-1234',
		},
		Active: true,
		Job: false,
		BalanceWithJobs: 120.5,
		BillAddr: {
			City: 'San Diego',
			Line1: '123 Beach Ave',
			PostalCode: '92109',
			Lat: '32.7157',
			Long: '-117.1611',
			CountrySubDivisionCode: 'CA',
			Id: '5',
		},
		PreferredDeliveryMethod: 'Email',
		Taxable: true,
		PrintOnCheckName: "Alice's Ocean Shop",
		Balance: 120.5,
		Id: '10',
		MetaData: {
			CreateTime: '2023-06-11T14:20:00-07:00',
			LastUpdatedTime: '2024-08-22T10:30:00-07:00',
		},
	},
	{
		PrimaryEmailAddr: {
			Address: 'mike@mountaingear.com',
		},
		SyncToken: '3',
		domain: 'QBO',
		GivenName: 'Mike',
		DisplayName: "Mike's Mountain Gear",
		BillWithParent: false,
		FullyQualifiedName: "Mike's Mountain Gear",
		CompanyName: "Mike's Mountain Gear",
		FamilyName: 'Summers',
		sparse: false,
		PrimaryPhone: {
			FreeFormNumber: '(720) 555-6789',
		},
		Active: true,
		Job: false,
		BalanceWithJobs: 200.0,
		BillAddr: {
			City: 'Denver',
			Line1: '789 Rocky Rd',
			PostalCode: '80202',
			Lat: '39.7392',
			Long: '-104.9903',
			CountrySubDivisionCode: 'CO',
			Id: '8',
		},
		PreferredDeliveryMethod: 'Print',
		Taxable: false,
		PrintOnCheckName: "Mike's Mountain Gear",
		Balance: 200.0,
		Id: '15',
		MetaData: {
			CreateTime: '2021-03-15T09:45:00-07:00',
			LastUpdatedTime: '2022-11-10T16:55:00-07:00',
		},
	},
	{
		PrimaryEmailAddr: {
			Address: 'jenny@urbanbikes.com',
		},
		SyncToken: '7',
		domain: 'QBO',
		GivenName: 'Jenny',
		DisplayName: "Jenny's Urban Bikes",
		BillWithParent: false,
		FullyQualifiedName: "Jenny's Urban Bikes",
		CompanyName: "Jenny's Urban Bikes",
		FamilyName: 'Miller',
		sparse: false,
		PrimaryPhone: {
			FreeFormNumber: '(312) 555-2468',
		},
		Active: true,
		Job: false,
		BalanceWithJobs: 75.25,
		BillAddr: {
			City: 'Chicago',
			Line1: '456 City St',
			PostalCode: '60601',
			Lat: '41.8781',
			Long: '-87.6298',
			CountrySubDivisionCode: 'IL',
			Id: '12',
		},
		PreferredDeliveryMethod: 'Email',
		Taxable: true,
		PrintOnCheckName: "Jenny's Urban Bikes",
		Balance: 75.25,
		Id: '20',
		MetaData: {
			CreateTime: '2022-07-04T12:15:00-07:00',
			LastUpdatedTime: '2023-05-29T08:00:00-07:00',
		},
	},
];
