name: Live API Validation
on:
  pull_request:
    branches: [main, develop]

jobs:
  live-tests:
    runs-on: ubuntu-latest
    env:
      QB_CLIENT_ID: ${{ secrets.QB_CLIENT_ID }}
      QB_CLIENT_SECRET: ${{ secrets.QB_CLIENT_SECRET }}
      SERIALIZED_TOKEN: ${{ secrets.SERIALIZED_TOKEN }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    strategy:
      matrix:
        test-file:
          - '__live-tests__/auth-provider.test.ts'
          - '__live-tests__/invoice-api.test.ts'

      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.1

      - name: Install dependencies
        run: bun install

      - name: Run ${{ matrix.test-file }}
        run: |
          bun test ${{ matrix.test-file }} --verbose
        continue-on-error: ${{ matrix.experimental }}

  final-status:
    needs: live-tests
    runs-on: ubuntu-latest
    steps:
      - name: Check test results
        run: |
          echo "Total failed jobs: ${{ needs.live-tests.result == 'failure' && '1' || '0' }}"
          if [[ "${{ needs.live-tests.result }}" == 'failure' ]]; then
            echo "::error::Some live tests failed - check individual test results"
            exit 1
          fi
