name: Publish

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed to get full git history for version detection

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.1

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test

      - name: Build package
        run: bun run build

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public

      - name: Push version tag
        run: |
          git push --follow-tags origin main
